trigger:
- master

pool:
  name: svr-cr
  vmImage: windows-latest

parameters:
  - name: MajorVersion
    type: number
    default: 1
  - name: MinorVersion
    type: number
    default: 0
  - name: RestoreBuildProjects
    type: string
    default: '**/*.csproj'
  - name: TestProjects
    type: string
    default: '**/*[Tt]ests/*.csproj'
  - name: AssemblyVersion
    type: string
    default: "0.0.0.0"
    values:
      - '$(assemblyVersion)'

variables:
  BuildConfiguration: 'Release'
  dotnetSdkVersion: 6.x
  buildDate: '$(Get-Date -Format yyyyMMdd:hhmmss)'
  baseVersion: '${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}'
  baseVersionBeta: '$(baseVersion).0-beta'
  ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
    versionRevision: $[counter(variables['baseVersion'], 0)]
    version: '$(baseversion).$(versionRevision)'
    assemblyVersion: '$(variables.version)'

  ${{ if and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
    versionRevision: $[counter(variables['baseVersionBeta'], 0)]
    version: '$(baseVersionBeta).$(versionRevision)'
    assemblyVersion: '$(baseVersion).0.$(versionRevision)'

  versionLong: '${{ parameters.MajorVersion }}.${{ parameters.MinorVersion }}.$(versionRevision).$(Build.BuildID)'

steps:
- checkout: self
  fetchDepth: 0

- task: JavaToolInstaller@0
  displayName: 'Use JDK'
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'C:\agents\svr-cr\jdk-11.0.18_windows-x64_bin.zip'
    cleanDestinationDirectory: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: '10ference'
    scannerMode: 'MSBuild'
    projectKey: '10ference_cars-rental-api'
    projectName: 'cars-rental-api'

- task: UseDotNet@2
  displayName: 'Use .NET'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: '${{ parameters.RestoreBuildProjects }}'

- script: >

    echo version : '${{ parameters.AssemblyVersion }}'
  displayName: "Assembly Version Generated"

- task: DotNetCoreCLI@2
  displayName: "Build project" 
  inputs:
    projects: '${{ parameters.RestoreBuildProjects }}'
    arguments: '--configuration $(BuildConfiguration) -p:VersionPrefix=${{ parameters.AssemblyVersion }}'

- task: SonarCloudAnalyze@1

- task: DotNetCoreCLI@2
  displayName: "Execute Tests" 
  inputs:
    command: test
    projects: '${{ parameters.TestProjects }}'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Publish artefacts" 
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: SonarCloudPublish@1
  displayName: "Publish SonarCloud Results" 
  inputs:
    pollingTimeoutSec: '300'