trigger:
- master

pool:
  name: svr-cr
  vmImage: ubuntu-latest

parameters:
  - name: RestoreBuildProjects
    type: string
    default: '**/*.csproj'
  - name: TestProjects
    type: string
    default: '**/*[Tt]ests/*.csproj'

variables:
  BuildConfiguration: 'Release'
  dotnetSdkVersion: 6.0.x


steps:  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: '10ference'
    scannerMode: 'MSBuild'
    projectKey: '10ference_cars-rental-api'
    projectName: 'cars-rental-api'

- task: UseDotNet@2
  displayName: 'Sélection de la version de .NET'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: "[Restore] Restoring packages.." 
  inputs:
    command: restore
    projects: '$(parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: "[Build] Building packages.." 
  inputs:
    projects: '$(parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: SonarCloudAnalyze@1

- task: DotNetCoreCLI@2
  displayName: "[Test] Executing Tests.." 
  inputs:
    command: test
    projects: '$(parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "[Publish] Publishing artefacts.." 
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'